#!/usr/bin/env bash
# This script displays numbers from 1 to 10
# If the number is 4, it prints "4 is your lucky number"
# If the number is 8, it prints "Bad luck 8"
# Otherwise, it prints the number

for i in {1..10}
do
  if [ "$i" -eq 4 ]
  then
    echo "4 is your lucky number"
  elif [ "$i" -eq 8 ]
  then
    echo "Bad luck 8"
  else
    echo "$i"
  fi
done
